### ISSUE TITLE
HeartSteps Watch-Face Authorization 2.0

### ISSUE THREAD

**Issue by nickdotreid** [kpwhri/heartsteps#155]
**Tasks**
- [x] API endpoint that creates new tokens POST */watch/pin*
- [x] API endpoint to show state of token GET */watch/pin/[pin goes here]*
- [x] API endpoint to connect a user id to a watch token POST */watch/pin/[pin goes here]*
- [x] Implement watch face unauthenticated state
- [x] Implement watch face has pin
- [x] Implement watch face has pin and is associated with user view

**Acceptance Criteria**
* When watchface app not authenticated, it will request a new token from the server
* Then watchface app will display token on watchface
* There is a settings page in the HeartSteps App that will allow the participant to enter the token from the watchface
* When the participant successfully enters the token the server will pair the participant with the watchface token.
* The watch face will "occasionally" check the server to see if it has a participant associated with the token
* When the server responds that a participant is associated with the token, the watch app displays the current time.

**Comment by nickdotreid** [comment]
Resources
* [Fitbit SDK](https://dev.fitbit.com/build/guides/)
* [Django REST Authentication](https://www.django-rest-framework.org/api-guide/authentication/)
* [HeartSteps Participant Authentication View](https://github.com/kpwhri/heartsteps/blob/master/server/participants/views.py#L30)

**Comment by nickdotreid** [comment]
We have received code from jake -- [Beta-HS](https://github.com/jkhuangg/Beta-HS/)

I'm marking this as done to clean up a little.
