### ISSUE TITLE
Improve walking suggestion decision exports

### ISSUE THREAD

**Issue by nickdotreid** [kpwhri/heartsteps#167]
The goal of this ticket is to improve how quickly walking suggestion decisions are exported. The goal of this ticket is to make the walking suggestion export fast enough to be included in the nightly data export.

**Tasks**
- [x] Add export walking suggestions to export user data task
- [x] Remove step count queries as that can be computed separately
- [x] Optimize unavailable reasons as part of main query
- [x] Collect related notification and events as part of main query
- [x] Add timezone to each row
- [x] Localize all times to timezone of walking suggestion decision
- [x] Add notification message, title, and id
- [x] Collect location information for query
- [x] Collect weather location for query

**Comment by nickdotreid** [comment]
I've started working on this, and have removed a bunch of information that will be re-entered.

So far I've decreased export time for the participant 'test-nickreid' from 30-ish minutes to less than 2 minutes.

**Comment by pengliao** [comment]
Currently the datasets for the location, anti-sedenatary and adherence are not exported in the data dump. We are also planning to add a spreadsheet for the complete days in the dump/

**Comment by nickdotreid** [comment]
@pengliao I think I found the bug, and should have just fixed it. Let's check the status of the exports tomorrow morning.

**Comment by pengliao** [comment]
@nickdotreid  I just check the data export.  I see the "anti-sedentary-decisions" is now being exported. However, I still don't see the location and the adherence datasets in there.

**Comment by pengliao** [comment]
@nickdotreid Yes, I am referring to the exported CSV files. In the previous nightly data dump, for each participant we have a csv file named "xxxx.adherence_metrics.csv". However, this csv file is not currently being exported.

**Comment by nickdotreid** [comment]
@pengliao - yes the adherence file isn't being exported currently -- it was
a pretty messy export. I'd rather create new files with more streamlined
data. I'll start a seperate ticket for that
