### ISSUE TITLE
No notification is coming, Fitbit auth error

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#315]
**Describe the bug**
* A tester (eric-0002) is not getting a notification.
* For the same user, Fitbit auth fails.

**To Reproduce**
1. Open App

**Expected behavior**
The dashboard is shown with today's activity.

**Screenshots**
![Screenshot_20220215-082728_JustWalk](https://user-images.githubusercontent.com/76829735/154119922-41700e81-4fbf-4719-8f07-f7236c737643.jpg)
![Screenshot_20220215-082758_JustWalk](https://user-images.githubusercontent.com/76829735/154119927-4603c2b6-d742-4a77-a286-ed4f2a8495da.jpg)
![Screenshot_20220215-082831_JustWalk](https://user-images.githubusercontent.com/76829735/154119931-65e214a9-b17b-4665-873d-551934e553fe.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A42
 - OS: Android
 - Version: One

**Todo**
- [x] Check the API server destination of the app on the play store

*** Fitbit Auth Check ***
- [x] Check Fitbit account in the server
- [x] Compare them with previous accounts (eric-0001)
- [x] See if the Fitbit auth is correct and update is coming in correctly.
- [x] Create another account (eric-0005) and link eric-0002's fitbit account with eric-0005
- [x] Log in with eric-0005
- [x] Check the Fitbit updates: They're coming in well
- [x] Check with Eric-0005 and see if it is reproducible -> not reproducible
- [x] Reproduce with Eric-0002

*** Notification Check ***
- [x] Log in with another account, on the other phone, send the notification
- [x] Try to send a notification to eric-0002, see if he receives
- [x] See device table logs
- [x] Ask him to log out, log back in, and turn on the notification.

**Comment by jup014** [comment]
This is solved after logging out and re-login. It seems like one of the developers stole the session key.

Closing the issue.
