### ISSUE TITLE
If a new device is registered for notification, remove other participant's active device with same ID

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#324]
**Describe the bug**
Even if somebody has logged out, the server still has the notification device ID. Thus, if the server sends a notification to the ID, the device owner will receive a notification, unless the user deletes the app.

Even if the user logs in with another account, the phone's token will remain the same. Thus, if the server tries to send a notification to the old participant, the same phone will receive the notification.

Moreover, the notification contains all stateless information (e.g. uuid) to fetch everything about the notification, the notification is somewhat reachable.

**To Reproduce**
In the same phone,

1. Log in as account A
2. Enable notification
3. Log out
4. Log in as account B
5. Enable notification
6. In the server, send a notification to account A

**Expected behavior**
The phone shouldn't get a notification. 

**ToDo**
- [x] If somebody logs in with notification enabled, inactivate all other devices with the same ID.
- [x] Test
- [x] If somebody logs out, inactivate the Device object.
- [x] Test
- [x] Inactivate all the old devices in the server - maintain only one device per device token active
- [x] Test

**Comment by patrick9958** [comment]
leaving a note here so I don't forget: the push_messages.tests.test_views.test_register_device should check for multiple devices upon adding a device and automatically inactivate all other devices on same user

**Comment by jup014** [comment]
And also, you got to deactivate all other Devices with same device token regardless of the user, additionally.

By doing that (and what you proposed below), we can assure


  1.  This user has only one active device
  2.  This device belongs to only one user

I’m not looking at the code right now, so I’m not 100% sure if the Device has Participant FK or User FK. But I think you got the idea.

Thanks,

JP

From: Patrick Neggie ***@***.***>
Date: Thursday, March 3, 2022 at 12:56
To: kpwhri/heartsteps ***@***.***>
Cc: Junghwan Park ***@***.***>, Author ***@***.***>
Subject: Re: [kpwhri/heartsteps] If a new device is registered for notification, remove other participant's active device with same ID (Issue #324)

leaving a note here so I don't forget: the push_messages.tests.test_views.test_register_device should check for multiple devices upon adding a device and automatically inactivate all other devices on same user
